FROM gradle:8.5.0-jdk17

USER root

# Install necessary packages – Docker, kubectl, argocd

#Docker
RUN apt-get update && \
    apt-get install -y docker.io curl unzip && \
    apt-get clean

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# Install argocd
RUN curl -sSl -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && \
    chmod +x /usr/local/bin/argocd

#Allow docekr inside docker
VOLUME /var/run/docker.sock

USER gradle