version: "3.8"

services:
  coffeehouse:
    image: ${REGISTRY}:${IMAGE_TAG}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: coffeehouse_app
    ports:
      - "8054:8054"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/coffeehouse
    networks:
      - coffeehouse_net
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.75"
          memory: 768M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - coffeehouse_net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.5"
          memory: 2048M
        reservations:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_dashboard
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin

    depends_on:
      - mongo
    networks:
      - coffeehouse_net
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: on-failure

volumes:
  mongo_data:

networks:
  coffeehouse_net: