//this jenkinsfile is for the deployement of the coffeehouse application using the GitOps–ArgoCD approach.  
pipeline {
    agent any

    environment {
        REGISTRY = 'devamkumar/coffeehouse'
        IMAGE_TAG = "${BUILD_NUMBER}"
        DEPLOYMENT_FILE = 'kubernetesFiles/coffeehouse-deployment.yaml'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh './gradlew clean build -x test'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${REGISTRY}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(
                credentialsId: 'docker-credentials-id',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
                )]) {
                    script {
                        sh """
                        #!/bin/bash
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${REGISTRY}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }
        stage('Update K8s Manifest') {
            steps {
                script {
                    sh """
                    sed -i 's|image: ${REGISTRY}:.*|image: ${REGISTRY}:${IMAGE_TAG}|' ${DEPLOYMENT_FILE}
                    cat  ${DEPLOYMENT_FILE}
                    """
                }
            }
        }
        stage('Commit & Push YAML') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'git-credentials-id',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    sh """
                    git config user.email "ci@jenkins.com"
                    git config user.name "Jenkins CI"
                    git add ${DEPLOYMENT_FILE}
                    git commit -m "🔄 Update image tag to ${IMAGE_TAG}"
                    git remote -v
                    git push https://${GIT_USER}:${GIT_PASS}@github.com/DevamKumar/CoffeeHouse.git HEAD:master
                    """
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
